// Vue JS/lab2/src/components/pages/studentDetails.vue
<template>
    <div class="card col-md-6 mx-auto card-text">
        <div class="d-flex">
            <div class="col-md-6 border-cafe align-items-center">
                <img class="card-img-top rounded align" src="@/assets/student.png"
                    alt="student image"  style="height: 100%;padding: 3%;">
            </div>
            <div class="col-md-6 text-center border-cafe py-5">
                <div class="The">
                    <div class="line"></div>
                    <h2 class="text-style"> Student </h2>
                </div>
                <h1 class="text-cafe text-style">
                    {{Student.name}}
                </h1>

                <p>Age : {{Student.age}}</p>
                <p>Email : {{Student.email}}</p>
                <p>Phone : {{Student.phone}}</p>
                <p>Grade : {{Student.grade}}</p>
                
                <div>
                    <span class="bg-light w-auto px-3 rounded-5" style="font-family: 'Brush Script MT', cursive;">
                    ID : {{Student.id}}
                    </span>  
                </div>
            </div>
        </div>
    </div>

</template>

<script>
    import axios from 'axios';
    export default {
        name: "studentDetails",
        created(){
            this.getStudentById()
        },
        data(){
            return{
                Student:{
                    id: '',
                    name: '',
                    email: '',
                    age: '',
                    phone: '',
                    grade: ''
                }
            }
        },
        methods:{
            getStudentById(){
                this.id = this.$route.params.id;
                axios
                .get(` http://localhost:3200/students/${this.id}`)
                .then((res)=>{
                    this.Student.id = res.data.id
                    this.Student.name = res.data.name
                    this.Student.email = res.data.email
                    this.Student.age = res.data.age
                    this.Student.phone = res.data.phone
                    this.Student.grade = res.data.grade
                })
                .catch((err)=>console.log(err))
                },
                back(){
                    this.$router.push('/students')
            }
        }
    }
</script>

<style scoped>
</style>

// Angular Framework/Lab5/src/app/Components/student-details/student-details.component.ts
import { Component ,OnInit} from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { StudentsService } from 'src/app/Services/students.service';

@Component({
  selector: 'app-student-details',
  templateUrl: './student-details.component.html',
  styleUrls: ['./student-details.component.css']
})
export class StudentDetailsComponent implements OnInit{
  ID:any;
  Student:any;

  constructor(myRoute:ActivatedRoute, public myService : StudentsService){
    this.ID = myRoute.snapshot.params["id"];
  }

  ngOnInit(): void {
    this.myService.GetStudentById(this.ID).subscribe({
      next:(data)=>{
        this.Student = data;
      },
      error:(err)=>{},
    })
  }
}

<div *ngIf="Student;else spinner" class="card col-md-6 mx-auto">
  <div class="d-flex">
      <div class="col-md-6 border">
          <img class="card-img-top rounded" src="./assets/Images/student.png"
              alt="student image">
      </div>
      <div class="col-md-6 text-center border py-5">
          <div class="The">
              <div class="line"></div>
              <h2 style="font-family: 'Brush Script MT', cursive; font-size:2.3rem"> Student </h2>
          </div>
          <h1>
              {{Student.name}}
          </h1>

          <p>Age : {{Student.age}}</p>
          <p>Email : {{Student.email}}</p>
          <p>Phone : {{Student.phone}}</p>
          <p>Grade : {{Student.grade}}</p>
          
          <div>
            <span class="bg-light w-auto px-3 rounded-5" style="font-family: 'Brush Script MT', cursive;">
              ID : {{Student.id}}
            </span>  
          </div>
      </div>
  </div>
</div>

<ng-template #spinner>
  <app-spinner></app-spinner>
</ng-template>
